### ISSUE TITLE
点击button报错且样式显示不全，是否是版本问题

### ISSUE THREAD

**Issue by shikuaiqian** [byk04712/weapp-popover#1]
调试库用不一样的版本显示不一样，然后点击button会报
TypeError: Cannot read property 'width' of null
    at e.wx.createSelectorQuery.selectViewport.scrollOffset.view (http://127.0.0.1:32845/appservice/pages/components/popover.js:42:31)
    at http://127.0.0.1:32845/appservice/__dev__/WAService.js:9:14953
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:32845/appservice/__dev__/WAService.js:9:14901
    at http://127.0.0.1:32845/appservice/__dev__/WAService.js:9:13058
    at e.(anonymous function) (http://127.0.0.1:32845/appservice/__dev__/WAService.js:4:2997)
    at e (http://127.0.0.1:32845/appservice/appservice?t=1556178569643:1315:20972)
    at r.registerCallback.t (http://127.0.0.1:32845/appservice/appservice?t=1556178569643:1315:21157)
    at l.forEach.t (http://127.0.0.1:32845/appservice/appservice?t=1556178569643:1315:1581)
    at Array.forEach (<anonymous>)
错误。
都已按照GitHub下的操作复制文件，能够显示click me

**Comment by byk04712** [comment]
@shikuaiqian   应该是的吧，这个我都有蛮久没有更新。
